//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NNR.Web
{
    using System;
    using System.Collections.Generic;
    
    public partial class Invoice
    {
        public int Id { get; set; }
        public string UserId { get; set; }
        public System.DateTime InvoiceDate { get; set; }
        public System.DateTime DueDate { get; set; }
        public int TermQBID { get; set; }
        public Nullable<int> Crew { get; set; }
        public Nullable<int> TaxId { get; set; }
        public Nullable<int> DiscountId { get; set; }
        public Nullable<decimal> AmountReceived { get; set; }
        public Nullable<decimal> Balance { get; set; }
        public int ProductId { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual Discount Discount { get; set; }
        public virtual Product Product { get; set; }
        public virtual Tax Tax { get; set; }
        public virtual Term Term { get; set; }
    }
}
