//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NNR.Web
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserQbUser
    {
        public int Id { get; set; }
        public string UserId { get; set; }
        public int QbUserId { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual QbUser QbUser { get; set; }
    }
}
