//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NNR.Web
{
    using System;
    using System.Collections.Generic;
    
    public partial class userstable
    {
        public int Id { get; set; }
        public string Username { get; set; }
        public Nullable<System.DateTime> Starttime { get; set; }
        public Nullable<System.DateTime> Endtime { get; set; }
        public Nullable<int> Ideltime { get; set; }
        public string Machinename { get; set; }
    }
}
