//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntuitSampleMVC.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblEmpEvaluation
    {
        public System.Guid PK_EvaluationID { get; set; }
        public Nullable<System.Guid> FK_Org_EmpID { get; set; }
        public Nullable<System.Guid> FK_TemplateID { get; set; }
        public string Eval_Doc_Path { get; set; }
        public Nullable<int> Processed { get; set; }
        public string Employer_Eval { get; set; }
        public string Employee_Eval { get; set; }
        public Nullable<bool> Only_Admin { get; set; }
        public string Eval_Grade { get; set; }
        public string Superv_Comments { get; set; }
        public Nullable<System.DateTime> Emp_Signed_Date { get; set; }
        public Nullable<System.DateTime> Supervisor_Signed_Date { get; set; }
        public string Summary1 { get; set; }
        public string Summary2 { get; set; }
        public Nullable<bool> ActiveFlag { get; set; }
        public string Rec_CreatedBy { get; set; }
        public Nullable<System.DateTime> Rec_CreatedDate { get; set; }
        public string Rec_ModifiedBy { get; set; }
        public Nullable<System.DateTime> Rec_ModifiedDate { get; set; }
    
        public virtual tblOrgEmployee tblOrgEmployee { get; set; }
        public virtual tblOrgEmployee tblOrgEmployee1 { get; set; }
        public virtual tblRatingTemplate tblRatingTemplate { get; set; }
        public virtual tblRatingTemplate tblRatingTemplate1 { get; set; }
    }
}
