//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntuitSampleMVC.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblOrgClientType
    {
        public System.Guid PK_Org_ClientTypeID { get; set; }
        public Nullable<System.Guid> FK_OrgID { get; set; }
        public string Org_ClientType { get; set; }
        public string Rec_CreatedBy { get; set; }
        public System.DateTime Rec_CreatedDate { get; set; }
        public string Rec_ModifiedBy { get; set; }
        public System.DateTime Rec_ModifiedDate { get; set; }
        public bool ActiveFlag { get; set; }
    
        public virtual tblOrganization tblOrganization { get; set; }
        public virtual tblOrganization tblOrganization1 { get; set; }
        public virtual tblOrganization tblOrganization2 { get; set; }
        public virtual tblOrganization tblOrganization3 { get; set; }
        public virtual tblOrganization tblOrganization4 { get; set; }
    }
}
