//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntuitSampleMVC.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblOrgEmployeeProjDet
    {
        public System.Guid PK_Org_Emp_ProjDetID { get; set; }
        public System.Guid FK_Org_EmpID { get; set; }
        public Nullable<System.DateTime> ProjStaratDt { get; set; }
        public Nullable<System.DateTime> ProjEndDt { get; set; }
        public string vendor1 { get; set; }
        public string vendor2 { get; set; }
        public string Client { get; set; }
        public Nullable<decimal> BillRate { get; set; }
        public Nullable<int> BillingCycle { get; set; }
        public string BillingContact { get; set; }
        public string BillingEmail { get; set; }
        public Nullable<System.DateTime> LastInvoiceDt { get; set; }
        public Nullable<System.DateTime> NextInvoiceDt { get; set; }
        public Nullable<bool> ActiveFlag { get; set; }
    }
}
