//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntuitSampleMVC.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblOrganization
    {
        public tblOrganization()
        {
            this.tblOrgClientTypes = new HashSet<tblOrgClientType>();
            this.tblOrgClientTypes1 = new HashSet<tblOrgClientType>();
            this.tblOrgClientTypes2 = new HashSet<tblOrgClientType>();
            this.tblOrgClientTypes3 = new HashSet<tblOrgClientType>();
            this.tblOrgClientTypes4 = new HashSet<tblOrgClientType>();
            this.tblOrgCustomers = new HashSet<tblOrgCustomer>();
            this.tblOrgCustomers1 = new HashSet<tblOrgCustomer>();
            this.tblOrgCustomers2 = new HashSet<tblOrgCustomer>();
            this.tblOrgEmployees = new HashSet<tblOrgEmployee>();
            this.tblOrgEmployees1 = new HashSet<tblOrgEmployee>();
            this.tblOrgEmployees2 = new HashSet<tblOrgEmployee>();
            this.tblOrgRoles = new HashSet<tblOrgRole>();
            this.tblOrgRoles1 = new HashSet<tblOrgRole>();
            this.tblOrgRoles2 = new HashSet<tblOrgRole>();
            this.tblOrgVendors = new HashSet<tblOrgVendor>();
            this.tblOrgVendors1 = new HashSet<tblOrgVendor>();
            this.tblOrgVendors2 = new HashSet<tblOrgVendor>();
        }
    
        public System.Guid Pk_OrgID { get; set; }
        public string Org_Name { get; set; }
        public string Org_Address1 { get; set; }
        public string Org_Address2 { get; set; }
        public string Org_City { get; set; }
        public string Org_State { get; set; }
        public string Org_PostalCode { get; set; }
        public string Org_Phone_ { get; set; }
        public string Org_EmailID { get; set; }
        public string Org_Fax { get; set; }
        public string Org_Website_URL { get; set; }
        public string Rec_CreatedBy { get; set; }
        public System.DateTime Rec_CreatedDate { get; set; }
        public string Rec_ModifiedBy { get; set; }
        public System.DateTime Rec_ModifiedDate { get; set; }
    
        public virtual ICollection<tblOrgClientType> tblOrgClientTypes { get; set; }
        public virtual ICollection<tblOrgClientType> tblOrgClientTypes1 { get; set; }
        public virtual ICollection<tblOrgClientType> tblOrgClientTypes2 { get; set; }
        public virtual ICollection<tblOrgClientType> tblOrgClientTypes3 { get; set; }
        public virtual ICollection<tblOrgClientType> tblOrgClientTypes4 { get; set; }
        public virtual ICollection<tblOrgCustomer> tblOrgCustomers { get; set; }
        public virtual ICollection<tblOrgCustomer> tblOrgCustomers1 { get; set; }
        public virtual ICollection<tblOrgCustomer> tblOrgCustomers2 { get; set; }
        public virtual ICollection<tblOrgEmployee> tblOrgEmployees { get; set; }
        public virtual ICollection<tblOrgEmployee> tblOrgEmployees1 { get; set; }
        public virtual ICollection<tblOrgEmployee> tblOrgEmployees2 { get; set; }
        public virtual ICollection<tblOrgRole> tblOrgRoles { get; set; }
        public virtual ICollection<tblOrgRole> tblOrgRoles1 { get; set; }
        public virtual ICollection<tblOrgRole> tblOrgRoles2 { get; set; }
        public virtual ICollection<tblOrgVendor> tblOrgVendors { get; set; }
        public virtual ICollection<tblOrgVendor> tblOrgVendors1 { get; set; }
        public virtual ICollection<tblOrgVendor> tblOrgVendors2 { get; set; }
        public virtual tblState tblState { get; set; }
    }
}
