//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntuitSampleMVC.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblOrgRole
    {
        public tblOrgRole()
        {
            this.tblOrgEmployees = new HashSet<tblOrgEmployee>();
            this.tblOrgEmployees1 = new HashSet<tblOrgEmployee>();
            this.tblOrgEmployees2 = new HashSet<tblOrgEmployee>();
            this.tblRolePermissions = new HashSet<tblRolePermission>();
        }
    
        public System.Guid PK_Org_RoleID { get; set; }
        public Nullable<System.Guid> FK_OrgID { get; set; }
        public string Org_Role_Name { get; set; }
        public string Org_Role_Description { get; set; }
        public bool ActiveFlag { get; set; }
    
        public virtual tblOrganization tblOrganization { get; set; }
        public virtual tblOrganization tblOrganization1 { get; set; }
        public virtual tblOrganization tblOrganization2 { get; set; }
        public virtual ICollection<tblOrgEmployee> tblOrgEmployees { get; set; }
        public virtual ICollection<tblOrgEmployee> tblOrgEmployees1 { get; set; }
        public virtual ICollection<tblOrgEmployee> tblOrgEmployees2 { get; set; }
        public virtual ICollection<tblRolePermission> tblRolePermissions { get; set; }
    }
}
