//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntuitSampleMVC.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblOrgEmployee
    {
        public tblOrgEmployee()
        {
            this.tblEmpDocuments = new HashSet<tblEmpDocument>();
            this.tblEmpEvaluations = new HashSet<tblEmpEvaluation>();
            this.tblEmpEvaluations1 = new HashSet<tblEmpEvaluation>();
            this.tblEmployeeTimeOffs = new HashSet<tblEmployeeTimeOff>();
            this.tblProjects = new HashSet<tblProject>();
            this.tblTasks = new HashSet<tblTask>();
            this.tblTasks1 = new HashSet<tblTasks1>();
            this.tblTimeSheets = new HashSet<tblTimeSheet>();
            this.tblTimeSheets1 = new HashSet<tblTimeSheets1>();
        }
    
        public System.Guid PK_Org_EmpID { get; set; }
        public string Emp_Code { get; set; }
        public Nullable<System.Guid> FK_OrgID { get; set; }
        public string Emp_Fname { get; set; }
        public string Emp_MName { get; set; }
        public string Emp_Lname { get; set; }
        public string Emp_Prefix { get; set; }
        public string Emp_CellPhone { get; set; }
        public string Emp_HomePhone { get; set; }
        public string Emp_BusinessPhone { get; set; }
        public string Emp_EmailID { get; set; }
        public string Emp_AlternateEmail { get; set; }
        public string Emp_JobTitle { get; set; }
        public string Emp_LoginPwd { get; set; }
        public System.DateTime Emp_HireDate { get; set; }
        public Nullable<System.DateTime> Emp_TerminationDate { get; set; }
        public string Emp_Home_Address1 { get; set; }
        public string Emp_Home_Address2 { get; set; }
        public string Emp_Home_City { get; set; }
        public string Emp_Home_State { get; set; }
        public string Emp_Home_PostalCode { get; set; }
        public string Emp_Bus_Address1 { get; set; }
        public string Emp_Bus_Address2 { get; set; }
        public string Emp_Bus_City { get; set; }
        public string Emp_Bus_State { get; set; }
        public string Emp_Bus_PostalCode { get; set; }
        public Nullable<System.Guid> FK_Org_Roles { get; set; }
        public string Rec_CreatedBy { get; set; }
        public System.DateTime Rec_CreatedDate { get; set; }
        public string Rec_ModifiedBy { get; set; }
        public System.DateTime Rec_ModifiedDate { get; set; }
        public bool ActiveFlag { get; set; }
        public string Emp_Categ { get; set; }
        public Nullable<decimal> Emp_Salary { get; set; }
        public string Doc_Number { get; set; }
        public Nullable<System.DateTime> Doc_ExpDate { get; set; }
        public string LCA_Number { get; set; }
        public Nullable<System.DateTime> LCA_ExpDate { get; set; }
        public string Perm_CertNumber { get; set; }
        public string I140_Number { get; set; }
        public string I485_Number { get; set; }
        public Nullable<short> Notify_QB { get; set; }
    
        public virtual ICollection<tblEmpDocument> tblEmpDocuments { get; set; }
        public virtual ICollection<tblEmpEvaluation> tblEmpEvaluations { get; set; }
        public virtual ICollection<tblEmpEvaluation> tblEmpEvaluations1 { get; set; }
        public virtual ICollection<tblEmployeeTimeOff> tblEmployeeTimeOffs { get; set; }
        public virtual tblOrganization tblOrganization { get; set; }
        public virtual tblOrganization tblOrganization1 { get; set; }
        public virtual tblOrganization tblOrganization2 { get; set; }
        public virtual tblState tblState { get; set; }
        public virtual tblState tblState1 { get; set; }
        public virtual tblOrgRole tblOrgRole { get; set; }
        public virtual tblOrgRole tblOrgRole1 { get; set; }
        public virtual tblOrgRole tblOrgRole2 { get; set; }
        public virtual ICollection<tblProject> tblProjects { get; set; }
        public virtual ICollection<tblTask> tblTasks { get; set; }
        public virtual ICollection<tblTasks1> tblTasks1 { get; set; }
        public virtual ICollection<tblTimeSheet> tblTimeSheets { get; set; }
        public virtual ICollection<tblTimeSheets1> tblTimeSheets1 { get; set; }
    }
}
