//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntuitSampleMVC.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblProject
    {
        public System.Guid PK_Org_ProjectID { get; set; }
        public System.Guid FK_Org_EmpID { get; set; }
        public string Proj_Code { get; set; }
        public string Proj_name { get; set; }
        public string Proj_Description { get; set; }
        public System.DateTime Proj_StartDate { get; set; }
        public System.DateTime Proj_EndDate { get; set; }
        public Nullable<System.Guid> FK_Client1 { get; set; }
        public Nullable<System.Guid> FK_Client2 { get; set; }
        public Nullable<System.Guid> FK_EndClient { get; set; }
        public Nullable<decimal> BillRate { get; set; }
        public Nullable<int> BillingCycle { get; set; }
        public Nullable<bool> OverTime_Allowed { get; set; }
        public Nullable<decimal> OverTime_Rate { get; set; }
        public string Rec_CreatedBy { get; set; }
        public System.DateTime Rec_CreatedDate { get; set; }
        public string Rec_ModifiedBy { get; set; }
        public System.DateTime Rec_ModifiedDate { get; set; }
        public bool ActiveFlag { get; set; }
        public string Terms { get; set; }
        public string EmailTo { get; set; }
        public string EmailCCTo { get; set; }
    
        public virtual tblOrgCustomer tblOrgCustomer { get; set; }
        public virtual tblOrgCustomer tblOrgCustomer1 { get; set; }
        public virtual tblOrgCustomer tblOrgCustomer2 { get; set; }
        public virtual tblOrgEmployee tblOrgEmployee { get; set; }
    }
}
