//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntuitSampleMVC.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPageDetail
    {
        public tblPageDetail()
        {
            this.tblRolePermissions = new HashSet<tblRolePermission>();
        }
    
        public System.Guid Pk_PageID { get; set; }
        public string Page_Name { get; set; }
        public string Page_Path { get; set; }
    
        public virtual ICollection<tblRolePermission> tblRolePermissions { get; set; }
    }
}
