//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntuitSampleMVC.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblReviewPeriod
    {
        public tblReviewPeriod()
        {
            this.tblRatingTemplates = new HashSet<tblRatingTemplate>();
            this.tblRatingTemplates1 = new HashSet<tblRatingTemplate>();
        }
    
        public System.Guid PK_ReviewPeriodID { get; set; }
        public string Period_Name { get; set; }
        public Nullable<System.DateTime> Start_Date { get; set; }
        public Nullable<System.DateTime> End_Date { get; set; }
        public bool ActiveFlag { get; set; }
        public string Rec_CreatedBy { get; set; }
        public Nullable<System.DateTime> Rec_CreatedDate { get; set; }
        public string Rec_ModifiedBy { get; set; }
        public Nullable<System.DateTime> Rec_ModifiedDate { get; set; }
    
        public virtual ICollection<tblRatingTemplate> tblRatingTemplates { get; set; }
        public virtual ICollection<tblRatingTemplate> tblRatingTemplates1 { get; set; }
    }
}
