//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntuitSampleMVC.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblRatingScale
    {
        public tblRatingScale()
        {
            this.tblRatingScaleTitles = new HashSet<tblRatingScaleTitle>();
            this.tblRatingScaleTitles1 = new HashSet<tblRatingScaleTitle>();
            this.tblRatingTemplates = new HashSet<tblRatingTemplate>();
            this.tblRatingTemplates1 = new HashSet<tblRatingTemplate>();
        }
    
        public System.Guid PK_RatingScaleID { get; set; }
        public string Rating_Scale { get; set; }
        public Nullable<bool> Single_Selection { get; set; }
        public bool ActiveFlag { get; set; }
        public string Rec_CreatedBy { get; set; }
        public Nullable<System.DateTime> Rec_CreatedDate { get; set; }
        public string Rec_ModifiedBy { get; set; }
        public Nullable<System.DateTime> Rec_ModifiedDate { get; set; }
    
        public virtual ICollection<tblRatingScaleTitle> tblRatingScaleTitles { get; set; }
        public virtual ICollection<tblRatingScaleTitle> tblRatingScaleTitles1 { get; set; }
        public virtual ICollection<tblRatingTemplate> tblRatingTemplates { get; set; }
        public virtual ICollection<tblRatingTemplate> tblRatingTemplates1 { get; set; }
    }
}
