//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntuitSampleMVC.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblRatingTemplate
    {
        public tblRatingTemplate()
        {
            this.tblEmpEvaluations = new HashSet<tblEmpEvaluation>();
            this.tblEmpEvaluations1 = new HashSet<tblEmpEvaluation>();
            this.tblRatTemplQues = new HashSet<tblRatTemplQue>();
            this.tblRatTemplQues1 = new HashSet<tblRatTemplQue>();
        }
    
        public System.Guid PK_TemplateID { get; set; }
        public string Template_Name { get; set; }
        public Nullable<System.Guid> FK_RatingScaleID { get; set; }
        public Nullable<System.Guid> FK_ReviewPeriodID { get; set; }
        public string Instructions { get; set; }
        public Nullable<bool> ActiveFlag { get; set; }
        public string Rec_CreatedBy { get; set; }
        public Nullable<System.DateTime> Rec_CreatedDate { get; set; }
        public string Rec_ModifiedBy { get; set; }
        public Nullable<System.DateTime> Rec_ModifiedDate { get; set; }
        public string Summary_Title1 { get; set; }
        public string Summary_Title2 { get; set; }
    
        public virtual ICollection<tblEmpEvaluation> tblEmpEvaluations { get; set; }
        public virtual ICollection<tblEmpEvaluation> tblEmpEvaluations1 { get; set; }
        public virtual tblRatingScale tblRatingScale { get; set; }
        public virtual tblRatingScale tblRatingScale1 { get; set; }
        public virtual tblReviewPeriod tblReviewPeriod { get; set; }
        public virtual tblReviewPeriod tblReviewPeriod1 { get; set; }
        public virtual ICollection<tblRatTemplQue> tblRatTemplQues { get; set; }
        public virtual ICollection<tblRatTemplQue> tblRatTemplQues1 { get; set; }
    }
}
