//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntuitSampleMVC.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblRatingScaleTitle
    {
        public System.Guid PK_RatingScaleTitleID { get; set; }
        public Nullable<System.Guid> FK_RatingScaleID { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public Nullable<int> Rating_Order { get; set; }
        public bool ActiveFlag { get; set; }
        public string Rec_CreatedBy { get; set; }
        public Nullable<System.DateTime> Rec_CreatedDate { get; set; }
        public string Rec_ModifiedBy { get; set; }
        public Nullable<System.DateTime> Rec_ModifiedDate { get; set; }
    
        public virtual tblRatingScale tblRatingScale { get; set; }
        public virtual tblRatingScale tblRatingScale1 { get; set; }
    }
}
