//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntuitSampleMVC.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblRolePermission
    {
        public System.Guid PK_RolePermission_ID { get; set; }
        public System.Guid Fk_PageID { get; set; }
        public string PermissionType { get; set; }
        public System.Guid FK_Org_RoleID { get; set; }
        public string Rec_CreatedBy { get; set; }
        public System.DateTime Rec_CreatedDate { get; set; }
        public string Rec_ModifiedBy { get; set; }
        public System.DateTime Rec_ModifiedDate { get; set; }
        public bool ActiveFlag { get; set; }
    
        public virtual tblOrgRole tblOrgRole { get; set; }
        public virtual tblPageDetail tblPageDetail { get; set; }
    }
}
