//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntuitSampleMVC.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblState
    {
        public tblState()
        {
            this.tblOrganizations = new HashSet<tblOrganization>();
            this.tblOrgCustomers = new HashSet<tblOrgCustomer>();
            this.tblOrgCustomers1 = new HashSet<tblOrgCustomer>();
            this.tblOrgEmployees = new HashSet<tblOrgEmployee>();
            this.tblOrgEmployees1 = new HashSet<tblOrgEmployee>();
            this.tblOrgVendors = new HashSet<tblOrgVendor>();
            this.tblOrgVendors1 = new HashSet<tblOrgVendor>();
        }
    
        public string StateID { get; set; }
        public string State { get; set; }
    
        public virtual ICollection<tblOrganization> tblOrganizations { get; set; }
        public virtual ICollection<tblOrgCustomer> tblOrgCustomers { get; set; }
        public virtual ICollection<tblOrgCustomer> tblOrgCustomers1 { get; set; }
        public virtual ICollection<tblOrgEmployee> tblOrgEmployees { get; set; }
        public virtual ICollection<tblOrgEmployee> tblOrgEmployees1 { get; set; }
        public virtual ICollection<tblOrgVendor> tblOrgVendors { get; set; }
        public virtual ICollection<tblOrgVendor> tblOrgVendors1 { get; set; }
    }
}
