//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntuitSampleMVC.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblTasks1
    {
        public System.Guid PK_TaskID { get; set; }
        public System.Guid FK_Org_EmpID { get; set; }
        public System.Guid FK_TimeSheetID { get; set; }
        public int Task_Number { get; set; }
        public System.DateTime Task_Date { get; set; }
        public string Task_Name { get; set; }
        public string Task_Description { get; set; }
        public string Rec_CreatedBy { get; set; }
        public System.DateTime Rec_CreatedDate { get; set; }
        public string Rec_ModifiedBy { get; set; }
        public System.DateTime Rec_ModifiedDate { get; set; }
    
        public virtual tblOrgEmployee tblOrgEmployee { get; set; }
    }
}
